name: Release new version

on: workflow_dispatch

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci
      - name: Set up git credentials
        run: |
          git config --global user.name 'ci'
          git config --global user.email 'deploy@l3vels.xyz'
      # - name: Prepare changes
      #   run: npm run release
      #   env:
      #     GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
      # - name: Commit and push changes
      #   run: |
      #     git add .
      #     git commit -m "Release version $(node -e "console.log(require('./package.json').version)")"
      #     git push --follow-tags
      - name: Publish the new version to npm
        run: | # Compare the latest version and the current version and publish only if the version changed
          if [ $(npm view @l3-lib/ui-core version) != $(node -e "console.log(require('./package.json').version)") ]; then npm run build && npm publish; else echo ''; fi;
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: latest
